INSERT INTO [Brand] VALUES('Salomon')
INSERT INTO [Brand] VALUES('7 For All Mankind')
INSERT INTO [Brand] VALUES('310 Motoring Apparel Company')
INSERT INTO [Brand] VALUES('575 Denim')
INSERT INTO [Brand] VALUES('8732 Apparel')
INSERT INTO [Brand] VALUES('Adam Jones Fashion')
INSERT INTO [Brand] VALUES('Alexander McQueen Fashion')
INSERT INTO [Brand] VALUES('American Apparel')
INSERT INTO [Brand] VALUES('Armani')
INSERT INTO [Brand] VALUES('Akademiks Clothing')
INSERT INTO [Brand] VALUES('Acne Studios')
INSERT INTO [Brand] VALUES('Adrienne Landau Fashion')
INSERT INTO [Brand] VALUES('All American Clothing')
INSERT INTO [Brand] VALUES('Apple Bottom Clothing')
INSERT INTO [Brand] VALUES('Aaron Chang Fashion')
INSERT INTO [Brand] VALUES('Azzure Denim')
INSERT INTO [Brand] VALUES('A.B.S. by Allen Schwartz')
INSERT INTO [Brand] VALUES('Anna Sui Fashions')
INSERT INTO [Brand] VALUES('Avirex Clothing')
INSERT INTO [Brand] VALUES('K-Swiss')
INSERT INTO [Brand] VALUES('Andrew Marc Fashion')
INSERT INTO [Brand] VALUES('Adidas')
INSERT INTO [Brand] VALUES('Reebok')
INSERT INTO [Brand] VALUES('AKOO Clothing')
INSERT INTO [Brand] VALUES('AND1')
INSERT INTO [Brand] VALUES('Al Wissam')
INSERT INTO [Brand] VALUES('Andrew Christian Clothing')
INSERT INTO [Brand] VALUES('Alviero Martini Fashions')
INSERT INTO [Brand] VALUES('A Bathing Ape')
INSERT INTO [Brand] VALUES('Abercrombie & Fitch')
INSERT INTO [Brand] VALUES('Artful Dodger Clothing')
INSERT INTO [Brand] VALUES('Antik Denim')
INSERT INTO [Brand] VALUES('Alice and Olivia LLC')
INSERT INTO [Brand] VALUES('Baby Phat')
INSERT INTO [Brand] VALUES('Bebe Stores')
INSERT INTO [Brand] VALUES('B.U.M Equipment')
INSERT INTO [Brand] VALUES('Badgley Mischka')
INSERT INTO [Brand] VALUES('BCBG Max Azria')
INSERT INTO [Brand] VALUES('BedHead Pajamas')
INSERT INTO [Brand] VALUES('Belabumbum Clothing')
INSERT INTO [Brand] VALUES('Bensoni Fashion House')
INSERT INTO [Brand] VALUES('Betsey Johnson Label')
INSERT INTO [Brand] VALUES('Billionaire Boys Club and Ice Cream')
INSERT INTO [Brand] VALUES('Blac Label')
INSERT INTO [Brand] VALUES('Banana Republic')
INSERT INTO [Brand] VALUES('Blue Tatoo Denim')
INSERT INTO [Brand] VALUES('Burberry')
INSERT INTO [Brand] VALUES('Bejeweled')
INSERT INTO [Brand] VALUES('Blank NYC')
INSERT INTO [Brand] VALUES('Blue Cult Jeans')
INSERT INTO [Brand] VALUES('Brette Sandler Swimwear')
INSERT INTO [Brand] VALUES('B.Chyll')
INSERT INTO [Brand] VALUES('BabaKul Clothing')
INSERT INTO [Brand] VALUES('Billionaire Mafia')
INSERT INTO [Brand] VALUES('Banfi Zambrelli')
INSERT INTO [Brand] VALUES('Bruno Magali')
INSERT INTO [Brand] VALUES('Byron Lars')
INSERT INTO [Brand] VALUES('Ben Sherman')
INSERT INTO [Brand] VALUES('Calvin Klein')
INSERT INTO [Brand] VALUES('Chanel')
INSERT INTO [Brand] VALUES('Chargrels Clothing')
INSERT INTO [Brand] VALUES('Ciara Couture Clothing')
INSERT INTO [Brand] VALUES('Coach')
INSERT INTO [Brand] VALUES('Christian Dior S.A.')
INSERT INTO [Brand] VALUES('Coogi Fashions')
INSERT INTO [Brand] VALUES('Chip and Pepper')
INSERT INTO [Brand] VALUES('Carhartt Clothing')
INSERT INTO [Brand] VALUES('Christian Audigier')
INSERT INTO [Brand] VALUES('Converse Shoes')
INSERT INTO [Brand] VALUES('Citizens of Humanity Jeans')
INSERT INTO [Brand] VALUES('Chick by Nicky Hilton')
INSERT INTO [Brand] VALUES('Cloudveil')
INSERT INTO [Brand] VALUES('Chic Jeans')
INSERT INTO [Brand] VALUES('Chloe')
INSERT INTO [Brand] VALUES('Columbia Sportswear Clothing')
INSERT INTO [Brand] VALUES('C & C California Clothing')
INSERT INTO [Brand] VALUES('Cordani Shoes')
INSERT INTO [Brand] VALUES('Christian Lacroix Fashions')
INSERT INTO [Brand] VALUES('Christian Louboutin')
INSERT INTO [Brand] VALUES('Cavi')
INSERT INTO [Brand] VALUES('Custo Barelona')
INSERT INTO [Brand] VALUES('DKNY')
INSERT INTO [Brand] VALUES('Diesel')
INSERT INTO [Brand] VALUES('Dolce & Gabbana')
INSERT INTO [Brand] VALUES('DSquared2 Clothing')
INSERT INTO [Brand] VALUES('Dooney & Bourke')
INSERT INTO [Brand] VALUES('DaKine')
INSERT INTO [Brand] VALUES('Diadora')
INSERT INTO [Brand] VALUES('Ed Hardy Clothing')
INSERT INTO [Brand] VALUES('Ella Moss Fashions')
INSERT INTO [Brand] VALUES('Eddie Bauer Clothing')
INSERT INTO [Brand] VALUES('Ellesse')
INSERT INTO [Brand] VALUES('Evisu')
INSERT INTO [Brand] VALUES('Ezekiel Clothing')
INSERT INTO [Brand] VALUES('Enyce Clothing')
INSERT INTO [Brand] VALUES('marc ecko enterprises')
INSERT INTO [Brand] VALUES('Etonic')
INSERT INTO [Brand] VALUES('Emilio Pucci')
INSERT INTO [Brand] VALUES('Esprit Holdings')
INSERT INTO [Brand] VALUES('Elie Tahari')
INSERT INTO [Brand] VALUES('English Laundry')
INSERT INTO [Brand] VALUES('Frankie B. Jeans')
INSERT INTO [Brand] VALUES('Fendi')
INSERT INTO [Brand] VALUES('French Connection')
INSERT INTO [Brand] VALUES('Fila Korea')
INSERT INTO [Brand] VALUES('FUBU Apparel')
INSERT INTO [Brand] VALUES('Fetish by Eve')
INSERT INTO [Brand] VALUES('Free People')
INSERT INTO [Brand] VALUES('Fred Perry')
INSERT INTO [Brand] VALUES('Gucci')
INSERT INTO [Brand] VALUES('Gap Inc.')
INSERT INTO [Brand] VALUES('Guess')
INSERT INTO [Brand] VALUES('G-Unit Clothing')
INSERT INTO [Brand] VALUES('Giordano')
INSERT INTO [Brand] VALUES('Girbaud')
INSERT INTO [Brand] VALUES('G-Star Raw')
INSERT INTO [Brand] VALUES('Grail Clothing')
INSERT INTO [Brand] VALUES('Guido & Mary')
INSERT INTO [Brand] VALUES('Gramicci')
INSERT INTO [Brand] VALUES('Helmut Lang')
INSERT INTO [Brand] VALUES('Hermes')
INSERT INTO [Brand] VALUES('Hugo Boss')
INSERT INTO [Brand] VALUES('Hanky Panky')
INSERT INTO [Brand] VALUES('House of Dereon')
INSERT INTO [Brand] VALUES('Helly Hansen')
INSERT INTO [Brand] VALUES('Iceberg History')
INSERT INTO [Brand] VALUES('IZOD')
INSERT INTO [Brand] VALUES('Indigo Red')
INSERT INTO [Brand] VALUES('Indivisual Clothing')
INSERT INTO [Brand] VALUES('InSport')
INSERT INTO [Brand] VALUES('Joe’s Jeans')
INSERT INTO [Brand] VALUES('Juicy Couture')
INSERT INTO [Brand] VALUES('Roberto Cavalli')
INSERT INTO [Brand] VALUES('J.Lo by Jennifer Lopez')
INSERT INTO [Brand] VALUES('Jimmy Choo')
INSERT INTO [Brand] VALUES('J. Crew Clothing')
INSERT INTO [Brand] VALUES('Jordache')
INSERT INTO [Brand] VALUES('Junko Yoshioka')
INSERT INTO [Brand] VALUES('Jovani')
INSERT INTO [Brand] VALUES('Ahnu')
INSERT INTO [Brand] VALUES('Vanz')
INSERT INTO [Brand] VALUES('Karl Lagerfeld')
INSERT INTO [Brand] VALUES('Kenneth Cole')
INSERT INTO [Brand] VALUES('KangaRoos')
INSERT INTO [Brand] VALUES('Karl Kani')
INSERT INTO [Brand] VALUES('Kangol')
INSERT INTO [Brand] VALUES('Kova & T')
INSERT INTO [Brand] VALUES('Keds')
INSERT INTO [Brand] VALUES('Kara Saun Fashion')
INSERT INTO [Brand] VALUES('LNA')
INSERT INTO [Brand] VALUES('Lifted Research Group')
INSERT INTO [Brand] VALUES('Lacoste')
INSERT INTO [Brand] VALUES('Live Mechanics')
INSERT INTO [Brand] VALUES('Levi Strauss & Co.')
INSERT INTO [Brand] VALUES('Lauren Conrad')
INSERT INTO [Brand] VALUES('Liz Claiborne')
INSERT INTO [Brand] VALUES('Louis Vuitton')
INSERT INTO [Brand] VALUES('Lucy Brand')
INSERT INTO [Brand] VALUES('Lipstick Bandit')
INSERT INTO [Brand] VALUES('Love Moschino')
INSERT INTO [Brand] VALUES('L.A.M.B.')
INSERT INTO [Brand] VALUES('Marc Jacobs')
INSERT INTO [Brand] VALUES('Margaret Howell')
INSERT INTO [Brand] VALUES('Maria Bonita Extra')
INSERT INTO [Brand] VALUES('Mecca')
INSERT INTO [Brand] VALUES('Michael Kors')
INSERT INTO [Brand] VALUES('Mavi Jeans')
INSERT INTO [Brand] VALUES('Miskeen Originals')
INSERT INTO [Brand] VALUES('Miu Miu')
INSERT INTO [Brand] VALUES('Moschino')
INSERT INTO [Brand] VALUES('Mossimo')
INSERT INTO [Brand] VALUES('Many Figured Million-Aire')
INSERT INTO [Brand] VALUES('Nine West')
INSERT INTO [Brand] VALUES('Nautica')
INSERT INTO [Brand] VALUES('Nike')
INSERT INTO [Brand] VALUES('Nicole Miller')
INSERT INTO [Brand] VALUES('Nicolas K.')
INSERT INTO [Brand] VALUES('Nation LTD.')
INSERT INTO [Brand] VALUES('Norma Kamali')
INSERT INTO [Brand] VALUES('Nudie Jeans')

INSERT INTO [Brand] VALUES('New Balance')
INSERT INTO [Brand] VALUES('Old Navy')
INSERT INTO [Brand] VALUES('Obey Clothing')
INSERT INTO [Brand] VALUES('Overland Equipment')
INSERT INTO [Brand] VALUES('One True Saxon')

INSERT INTO [Brand] VALUES('Oscar De La Renta')
INSERT INTO [Brand] VALUES('Perry Ellis')
INSERT INTO [Brand] VALUES('Paige Premium Denim')
INSERT INTO [Brand] VALUES('Puma')
INSERT INTO [Brand] VALUES('Paper Denim & Cloth')
INSERT INTO [Brand] VALUES('Prada')
INSERT INTO [Brand] VALUES('Pastelle by Kanye West')
INSERT INTO [Brand] VALUES('Plenty by Tracy Reece')
INSERT INTO [Brand] VALUES('Pelle Pelle')
INSERT INTO [Brand] VALUES('Playboy Clothing')
INSERT INTO [Brand] VALUES('Pepe Jeans')
INSERT INTO [Brand] VALUES('Parish Nation Clothing')
INSERT INTO [Brand] VALUES('Phat Farm')
INSERT INTO [Brand] VALUES('Pro Keds')
INSERT INTO [Brand] VALUES('PZI Jeans')
INSERT INTO [Brand] VALUES('Pastry Shoe Collection')
INSERT INTO [Brand] VALUES('Privacy Wear')
INSERT INTO [Brand] VALUES('Saucony')
